"""Backfill as queued jobs, started at startup or by hand (ADR-0024 §5, item 9).

A job asks for one channel's range. One worker takes the oldest `queued` job, fills its range and records
what it got; the `backfill_runs` rows it writes are the per-provider detail. A range can be queued or
running only once at a time (`backfill_jobs_open`), so startup and a chatter asking at the same moment
make one job.

Revision ID: 0003
Revises: 0002
"""

from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE backfill_jobs (
            id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            channel_id   text NOT NULL,
            from_ms      bigint NOT NULL,
            to_ms        bigint NOT NULL,
            requested_by text NOT NULL,      -- 'startup', 'chat:<user id>', or the API caller's label
            requested_at bigint NOT NULL,
            state        text NOT NULL DEFAULT 'queued'
                         CHECK (state IN ('queued', 'running', 'done', 'failed', 'cancelled')),
            started_at   bigint,
            finished_at  bigint,
            fetched      integer NOT NULL DEFAULT 0,
            inserted     integer NOT NULL DEFAULT 0,
            complete     boolean,
            error        text,
            CHECK (to_ms > from_ms)
        )
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX backfill_jobs_open ON backfill_jobs (channel_id, from_ms, to_ms)"
        " WHERE state IN ('queued', 'running')"
    )
    op.execute("CREATE INDEX backfill_jobs_channel ON backfill_jobs (channel_id, id DESC)")


def downgrade() -> None:
    op.execute("DROP TABLE backfill_jobs")
