-- schema `bot`: state and configuration (architecture §5, §6, §7, §9, §10; ADR-0006, 0007, 0009, 0010)
-- Conventions:
--   * timestamps are bigint milliseconds since the Unix epoch, not timestamptz: the code has dealt in
--     epoch ms since ADR-0003, and converting was deliberately left out of the Postgres port (ADR-0014)
--   * users are keyed by Twitch user_id, never login
--   * global (non-channel) rows use channel_id = '*', because a NULL would not dedupe in a primary key

-- ── Auth ─────────────────────────────────────────────────────────────────────
CREATE TABLE oauth_tokens (
    identity      text PRIMARY KEY,          -- 'bot' | 'broadcaster:<user_id>'
    user_id       text NOT NULL,
    login         text NOT NULL,
    access_token  text NOT NULL,
    refresh_token text,
    scopes        text NOT NULL DEFAULT '[]', -- JSON array
    expires_at    bigint,
    updated_at    bigint NOT NULL
);

CREATE TABLE api_keys (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          text NOT NULL,
    key_hash      text NOT NULL UNIQUE,      -- argon2/sha256 of the key; the key itself is never stored
    owner_user_id text,
    scopes        text NOT NULL DEFAULT '[]',
    created_at    bigint NOT NULL,
    last_used_at  bigint,
    revoked_at    bigint
);

-- ── Channels (ADR-0007) ─────────────────────────────────────────────────────
CREATE TABLE channels (
    channel_id             text PRIMARY KEY,
    login                  text NOT NULL,
    active                 boolean NOT NULL DEFAULT true,
    status                 text NOT NULL DEFAULT 'joined',  -- joined | parted | banned
    tier                   text NOT NULL DEFAULT 'basic',   -- basic | moderator | full
    capabilities           text NOT NULL DEFAULT '[]',      -- JSON array
    -- Cosmetic: the app always inserts the sign explicitly from lang.parser.DEFAULT_PREFIX.
    prefix                 text NOT NULL DEFAULT '🏜',
    reply_hold_ms          bigint NOT NULL DEFAULT 0,
    log_enabled            boolean NOT NULL DEFAULT true,
    history_backfill       boolean NOT NULL DEFAULT false,  -- opt-in (ADR-0008)
    quiet_errors           boolean NOT NULL DEFAULT false,
    cc_edit_notice         boolean NOT NULL DEFAULT false,
    timezone               text NOT NULL DEFAULT 'UTC',
    channel_var_write_role text NOT NULL DEFAULT 'moderator',
    grant_min_role         text NOT NULL DEFAULT 'moderator',
    publish_min_role       text NOT NULL DEFAULT 'moderator',
    create_min_role        text NOT NULL DEFAULT 'everyone',
    var_admin_role         text NOT NULL DEFAULT 'moderator',
    -- AutoMod-assisted filtering (architecture §9.3): off until a moderator turns it on, and it needs
    -- the moderator tier to do anything at all.
    automod_action         text NOT NULL DEFAULT 'off',     -- off | delete | timeout
    automod_timeout_s      bigint NOT NULL DEFAULT 600,
    joined_by              text,
    added_at               bigint NOT NULL,
    updated_at             bigint NOT NULL
);

-- ── Roles (ADR-0006) ────────────────────────────────────────────────────────
CREATE TABLE roles (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id text NOT NULL,                -- '*' = global
    name       text NOT NULL,
    rank       integer NOT NULL CHECK (rank BETWEEN 0 AND 10000),
    builtin    boolean NOT NULL DEFAULT false,
    created_by text,
    created_at bigint NOT NULL,
    UNIQUE (channel_id, name)
);

CREATE TABLE role_members (
    role_id    bigint NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    user_id    text NOT NULL,
    user_login text,                         -- login snapshot: admin listings need no Twitch lookup
    granted_by text,
    granted_at bigint NOT NULL,
    expires_at bigint,
    PRIMARY KEY (role_id, user_id)
);
CREATE INDEX ix_role_members_user ON role_members(user_id);

CREATE TABLE global_admins (                 -- bot_admin (rank 1000); bot_owner comes from config
    user_id    text PRIMARY KEY,
    user_login text,
    granted_by text NOT NULL,
    granted_at bigint NOT NULL
);

-- ── Policy: toggles, permissions, cooldowns, callbacks, ignore ──────────────
CREATE TABLE module_toggles (
    channel_id text NOT NULL,                -- '*' = global
    module     text NOT NULL,
    enabled    boolean NOT NULL,
    PRIMARY KEY (channel_id, module)
);

CREATE TABLE command_toggles (
    channel_id text NOT NULL,
    command    text NOT NULL,
    enabled    boolean,                      -- NULL = inherit
    log_level  text,                         -- NULL = spec default; off|errors|output|invocations|all
    PRIMARY KEY (channel_id, command)
);

CREATE TABLE command_rules (
    channel_id    text NOT NULL,
    command       text NOT NULL,
    required_role text,
    allowed_roles text,                      -- JSON array
    PRIMARY KEY (channel_id, command)
);

CREATE TABLE cooldown_rules (
    channel_id text NOT NULL,
    command    text NOT NULL,
    role       text NOT NULL,
    tier_s     integer NOT NULL CHECK (tier_s >= 0),
    user_s     integer NOT NULL CHECK (user_s >= 0),
    PRIMARY KEY (channel_id, command, role)
);

CREATE TABLE callbacks (
    channel_id     text NOT NULL,
    scope          text NOT NULL,            -- 'channel' | 'module:<name>' | 'command:<name>'
    kind           text NOT NULL CHECK (kind IN ('on_cooldown', 'on_denied')),
    expr           text NOT NULL,
    syntax_version text NOT NULL,
    updated_by     text,
    updated_at     bigint NOT NULL,
    PRIMARY KEY (channel_id, scope, kind)
);

CREATE TABLE ignore_list (
    channel_id text NOT NULL,                -- '*' = global
    user_id    text NOT NULL,
    user_login text,
    reason     text,
    added_by   text,
    added_at   bigint NOT NULL,
    PRIMARY KEY (channel_id, user_id)
);

-- ── Custom commands (ADR-0009) ──────────────────────────────────────────────
CREATE TABLE custom_commands (
    id              text PRIMARY KEY,        -- e.g. cc_7f3k2
    owner_user_id   text NOT NULL,
    owner_login     text,
    name            text NOT NULL,
    summary         text,
    description     text,
    params          text NOT NULL DEFAULT '[]',
    examples        text NOT NULL DEFAULT '[]',
    data_schema     text,
    current_version integer NOT NULL,
    visibility      text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'shareable')),
    status          text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'deleted', 'banned')),
    created_at      bigint NOT NULL,
    updated_at      bigint NOT NULL,
    UNIQUE (owner_user_id, name)
);
CREATE INDEX ix_cc_owner ON custom_commands(owner_user_id, status);

CREATE TABLE custom_command_versions (
    command_id     text NOT NULL REFERENCES custom_commands(id) ON DELETE CASCADE,
    version        integer NOT NULL,
    body           text NOT NULL,
    params         text NOT NULL DEFAULT '[]',
    syntax_version text NOT NULL,
    created_at     bigint NOT NULL,
    PRIMARY KEY (command_id, version)
);

CREATE TABLE custom_command_links (
    user_id    text NOT NULL,
    alias      text NOT NULL,
    command_id text NOT NULL REFERENCES custom_commands(id),
    created_at bigint NOT NULL,
    PRIMARY KEY (user_id, alias)
);
CREATE INDEX ix_cc_links_command ON custom_command_links(command_id);

CREATE TABLE custom_command_publications (
    channel_id         text NOT NULL,
    name               text NOT NULL,
    command_id         text NOT NULL REFERENCES custom_commands(id),
    published_by       text NOT NULL,
    status             text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled', 'orphaned')),
    cooldown_overrides text,
    required_role      text,
    last_run_version   integer,
    created_at         bigint NOT NULL,
    PRIMARY KEY (channel_id, name)
);
CREATE INDEX ix_cc_publications_command ON custom_command_publications(command_id);

-- ── Packs (ADR-0012) ────────────────────────────────────────────────────────
-- A channel stores one row per published pack, not one per member, so a member added later appears
-- immediately — the same live-edit rule as ADR-0009.
CREATE TABLE custom_command_packs (
    id            text PRIMARY KEY,          -- e.g. pk_7f3k2
    owner_user_id text NOT NULL,
    name          text NOT NULL,             -- also the module name for module toggles
    summary       text,
    status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'deleted')),
    created_at    bigint NOT NULL,
    updated_at    bigint NOT NULL,
    UNIQUE (owner_user_id, name)
);

CREATE TABLE custom_command_pack_members (
    pack_id    text NOT NULL REFERENCES custom_command_packs(id) ON DELETE CASCADE,
    command_id text NOT NULL REFERENCES custom_commands(id) ON DELETE CASCADE,
    added_at   bigint NOT NULL,
    PRIMARY KEY (pack_id, command_id)
);
CREATE INDEX ix_cc_pack_members_command ON custom_command_pack_members(command_id);

CREATE TABLE custom_command_pack_publications (
    channel_id   text NOT NULL,              -- '*' is every channel (ADR-0012 derived commands)
    pack_id      text NOT NULL REFERENCES custom_command_packs(id) ON DELETE CASCADE,
    published_by text NOT NULL,
    status       text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at   bigint NOT NULL,
    PRIMARY KEY (channel_id, pack_id)
);
CREATE INDEX ix_cc_pack_publications_channel ON custom_command_pack_publications(channel_id, status);

-- ── Variables (ADR-0010, variable-access-matrix.md) ─────────────────────────
CREATE TABLE variables (
    ns          text NOT NULL CHECK (ns IN ('chatter', 'channel', 'channel.chatter', 'publisher',
                                            'publisher.chatter', 'publisher.channel',
                                            'publisher.channel.chatter')),
    key1        text NOT NULL,
    key2        text NOT NULL DEFAULT '',
    key3        text NOT NULL DEFAULT '',
    name        text NOT NULL,
    value       text NOT NULL,               -- JSON
    updated_at  bigint NOT NULL,
    updated_by  text,
    updated_via text,
    PRIMARY KEY (ns, key1, key2, key3, name)
);
CREATE INDEX ix_variables_board ON variables(ns, key1, key2, name);

-- Grants follow the command, not the published name, so republishing a different command under the
-- same name cannot inherit the old grants (variable-access-matrix.md §4).
CREATE TABLE publication_write_grants (
    channel_id text NOT NULL,
    command_id text NOT NULL REFERENCES custom_commands(id) ON DELETE CASCADE,
    variable   text NOT NULL,                -- exact name, e.g. 'channel.chatter.points'; no wildcards
    granted_by text NOT NULL,
    granted_at bigint NOT NULL,
    PRIMARY KEY (channel_id, command_id, variable)
);

-- ── Triggers, timers, listeners (architecture §7) ───────────────────────────
CREATE TABLE triggers (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id     text NOT NULL,
    type           text NOT NULL,            -- redemption|raid|sub|resub|gift_sub|cheer|follow|stream_online|stream_offline|timer|listener
    match          text NOT NULL DEFAULT '{}',
    schedule       text,
    expr           text NOT NULL,
    syntax_version text NOT NULL,
    run_as_rank    integer NOT NULL,
    enabled        boolean NOT NULL DEFAULT true,
    log_level      text NOT NULL DEFAULT 'output',
    created_by     text NOT NULL,
    created_at     bigint NOT NULL,
    updated_at     bigint NOT NULL
);
CREATE INDEX ix_triggers_channel_type ON triggers(channel_id, type);

-- ── Badword filter (architecture §9) ────────────────────────────────────────
CREATE TABLE filters (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id  text NOT NULL,               -- '*' = global
    pattern     text NOT NULL,
    kind        text NOT NULL CHECK (kind IN ('word', 'wildcard', 'regex', 'allow')),
    category    text,
    action      text NOT NULL CHECK (action IN ('mask', 'replace', 'tag', 'block')),
    replacement text,
    enabled     boolean NOT NULL DEFAULT true,
    created_by  text,
    created_at  bigint NOT NULL
);
CREATE INDEX ix_filters_channel ON filters(channel_id, enabled);

-- ── Audit log (always on) ───────────────────────────────────────────────────
CREATE TABLE audit_log (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id    text,
    actor_user_id text,
    via           text NOT NULL,             -- chat | api | web | system
    action        text NOT NULL,
    target        text,
    before        text,
    after         text,
    at            bigint NOT NULL
);
CREATE INDEX ix_audit_channel_time ON audit_log(channel_id, at);

-- ── Built-in role seeds (global) ────────────────────────────────────────────
INSERT INTO roles (channel_id, name, rank, builtin, created_at) VALUES
    ('*', 'everyone',          0, true, 0),
    ('*', 'subscriber',       20, true, 0),
    ('*', 'vip',              60, true, 0),
    ('*', 'moderator',        80, true, 0),
    ('*', 'lead_moderator',   90, true, 0),
    ('*', 'broadcaster',     100, true, 0),
    ('*', 'bot_admin',      1000, true, 0),
    ('*', 'bot_owner',     10000, true, 0);
